#!/usr/bin/env python3
"""emit_collision_redirects.py — stop the flat .html shadowing the directory.

THE COLLISION
  Eleven slugs exist as BOTH a page and a section:

      morzine.html          → the station page   "Morzine · Village-station…"   ~1,850 words
      morzine/index.html    → the commune page   "Que faire à Morzine ?"        ~530 words

  Netlify resolves that pair by letting the flat file win, and 301s the
  directory away:

      /morzine/   301 → /morzine        (station page)
      /morzine    200                   (station page)

  So the commune page is built, deployed, listed in the sitemap — and
  unreachable. All 132 of them (11 slugs × 12 locales).

WHY THAT IS THE WRONG WINNER
  It inverts this site's own convention. Of 34 commune pages, the 23 with no
  flat-file twin resolve the other way round and work correctly:

      /annecy     301 → /annecy/
      /annecy/    200                   (commune page)

  Commune pages live at /<slug>/. The eleven are the anomaly, not the rule.

  The internal links agree, unanimously: all 3,036 `class="commune-link"`
  hrefs on the site use the trailing slash, and not one omits it. Every one of
  those links is currently redirected to a page it did not ask for. The commune
  pages also carry lieux the station pages never link — 14 of them on Chamonix
  alone (lac-blanc, lac-cornu, patinoire-richard-bozon…) — so the redirect is
  eating real internal-link surface, not a duplicate.

WHAT THIS EMITS
  A forced rewrite per collision, so the directory keeps its own URL:

      /morzine/    /morzine/index.html    200!

  200 (not 301): the commune page IS the resource at /<slug>/, it is not
  somewhere else. The `!` is required — without it Netlify's own resolution
  wins and the rule never fires, which is the whole bug.

  Both URLs then serve, each its own page, each already self-canonical
  (/morzine → station, /morzine/ → commune). Nothing is renamed, no content is
  dropped, no new URL is introduced for Google to rediscover, and the 132
  sitemap entries become true instead of being pruned.

  Generated from the filesystem, never hand-listed: a new station page over an
  existing commune (or the reverse) is covered by the next build, and a
  resolved collision drops out on its own.

VERIFY AFTER DEPLOY — this cannot be proven locally. Netlify's resolution order
is a platform behaviour, so the rule can only be confirmed against the live
site:

    curl -sI https://loisirs74.fr/morzine/  | head -1   # expect 200, not 301
    curl -s  https://loisirs74.fr/morzine/  | grep -o '<title>[^<]*'  # "Que faire à Morzine ?"
    curl -sI https://loisirs74.fr/morzine   | head -1   # expect 200 (station, unchanged)

Idempotent: the managed block is rewritten in place, never appended twice.

Usage:
    python3 scripts/emit_collision_redirects.py            # report, writes nothing
    python3 scripts/emit_collision_redirects.py --apply

2026 · Bleu canard édition · Edmaster & Claudius 🦆
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REDIRECTS = ROOT / "_redirects"

BEGIN = "# === BEGIN slug-collision rewrites (generated by scripts/emit_collision_redirects.py) ==="
END = "# === END slug-collision rewrites ==="
BLOCK_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.S)

HEADER = [
    BEGIN,
    "# A flat <slug>.html and a <slug>/ directory both exist. Netlify lets the",
    "# flat file win and 301s the directory away, which hides the commune page",
    "# behind the station page. These force the directory to keep its own URL.",
    "# Do not hand-edit: regenerated by build_all from the filesystem.",
]


def collisions():
    """(url_path, target_file) for every <slug>.html that shadows <slug>/index.html."""
    out = []
    bases = [("", ROOT)] + [(f"/{d.name}", d) for d in sorted(ROOT.iterdir())
                            if d.is_dir() and len(d.name) == 2]
    for prefix, base in bases:
        for page in sorted(base.glob("*.html")):
            section = base / page.stem / "index.html"
            if section.is_file():
                out.append((f"{prefix}/{page.stem}/", f"{prefix}/{page.stem}/index.html"))
    return out


def main():
    ap = argparse.ArgumentParser(description="Force directory URLs that a flat .html shadows.")
    ap.add_argument("--apply", action="store_true", help="write changes (default: report only)")
    args = ap.parse_args()

    pairs = collisions()
    if not pairs:
        print("emit_collision_redirects: no slug collisions — nothing to force")
        return 0

    # Pad each column to its OWN longest entry. Sharing one width lets a long
    # target run past it and butt straight into the status —
    # "…/index.html200!" — which Netlify cannot parse. Two spaces minimum,
    # always, so alignment can never eat the separator.
    uw = max(len(u) for u, _ in pairs) + 2
    tw = max(len(t) for _, t in pairs) + 2
    lines = HEADER + [f"{u:<{uw}}{t:<{tw}}200!" for u, t in pairs] + [END, ""]
    block = "\n".join(lines)

    text = REDIRECTS.read_text(encoding="utf-8")
    if BLOCK_RE.search(text):
        new = BLOCK_RE.sub(block, text, count=1)
    else:
        # top of file: Netlify takes the first match, and nothing above may
        # claim these paths first.
        head, _, rest = text.partition("\n")
        new = f"{head}\n\n{block}\n{rest.lstrip(chr(10))}"

    changed = new != text
    if changed and args.apply:
        REDIRECTS.write_text(new, encoding="utf-8")

    slugs = sorted({u.strip("/").split("/")[-1] for u, _ in pairs})
    verb = "wrote" if (changed and args.apply) else ("would write" if changed else "unchanged —")
    print(f"emit_collision_redirects: {verb} {len(pairs)} force rule(s) "
          f"for {len(slugs)} slug(s) across {len(pairs) // max(len(slugs), 1)} locale(s)")
    print(f"  {', '.join(slugs)}")
    if changed and not args.apply:
        print("  report only — re-run with --apply to write")
    return 0


if __name__ == "__main__":
    sys.exit(main())
